"""Explicit local execution contracts. Creating a draft never activates it."""
import math
import re
import uuid
from datetime import datetime, timezone
from pathlib import Path

REMOTE = 'https://github.com/mpriorust/legal-context-compression-repro.git'


def draft(path: Path, output: Path, mode='smoke', max_usd=1.0, max_requests=64, max_seconds=None):
    workspace = Path.cwd().resolve()
    output = output.expanduser().absolute()
    if output != output.resolve() or not output.is_relative_to(workspace) or output == workspace or output.exists():
        raise ValueError('Use a fresh output below this workspace')
    stamp = datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')
    fields = {
        'CONTRACT_ID':f'legal-repro-{mode}-{stamp}-{uuid.uuid4().hex[:8]}',
        'STATUS':'DRAFT', 'WORKSPACE':str(workspace), 'OUTPUT_ROOT':str(output),
        'ACTION':mode, 'API_KEY_ENV':'OPENROUTER_API_KEY',
        'MAX_USD':str(max_usd), 'MAX_REQUESTS':str(max_requests), 'MAX_SECONDS':str(max_seconds or (604800 if mode=='evaluate' else 3600)),
        'ALLOW_RESUME':'true', 'GITHUB_REMOTE':REMOTE, 'GITHUB_VISIBILITY':'private',
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open('x') as stream:
        stream.write('# Activate only after the owner approves these exact paths, actions and limits.\n')
        if mode=='publish':
            stream.write('# Credential scope: existing local gh GitHub login; create/push only this private repository.\n')
        else:
            stream.write('# Credential scope: OPENROUTER_API_KEY from the environment or WORKSPACE/.env only.\n')
            stream.write('# Upload selected QA prompts; no local model serving or GPU access.\n')
        stream.writelines(f'{key}: {value}\n' for key,value in fields.items())
    return {'contract':str(path.resolve()), **fields}


def load(path: Path, action: str):
    fields = {}
    lines = path.read_text().splitlines()
    for line in lines:
        if not line.strip() or line.startswith('#'):
            continue
        key, separator, value = line.partition(':')
        if not separator or key in fields:
            raise ValueError('Malformed or duplicate contract field')
        fields[key] = value.strip()
    required = {'CONTRACT_ID','STATUS','WORKSPACE','OUTPUT_ROOT','ACTION','API_KEY_ENV','MAX_USD','MAX_REQUESTS','MAX_SECONDS','ALLOW_RESUME','GITHUB_REMOTE','GITHUB_VISIBILITY'}
    if set(fields) != required or lines.count('STATUS: ACTIVE') != 1:
        raise PermissionError('An explicitly approved contract with exactly one STATUS: ACTIVE line is required')
    if not re.fullmatch(r'legal-repro-[a-z]+-\d{8}T\d{6}Z-[0-9a-f]{8}', fields['CONTRACT_ID']):
        raise ValueError('Contract ID must be unique and generated by legal-repro contract')
    workspace, output = Path(fields['WORKSPACE']), Path(fields['OUTPUT_ROOT'])
    if workspace != Path.cwd().resolve() or not workspace.is_absolute() or output != output.resolve() or not output.is_relative_to(workspace) or output == workspace:
        raise PermissionError('Contract workspace/output paths do not match this invocation')
    if fields['ACTION'] != action or fields['API_KEY_ENV'] != 'OPENROUTER_API_KEY':
        raise PermissionError('Contract does not authorize this action or credential')
    if fields['GITHUB_REMOTE'] != REMOTE or fields['GITHUB_VISIBILITY'] != 'private':
        raise PermissionError('Only the named private GitHub remote is allowed')
    budget = float(fields['MAX_USD'])
    if not math.isfinite(budget) or budget<=0 or int(fields['MAX_REQUESTS'])<1 or int(fields['MAX_SECONDS'])<1 or fields['ALLOW_RESUME'] not in ('true','false'):
        raise ValueError('Invalid execution limits')
    if action == 'smoke' and (budget>1 or int(fields['MAX_REQUESTS'])>64 or int(fields['MAX_SECONDS'])>3600):
        raise ValueError('Smoke contract exceeds the fixed $1 / 64 requests / one-hour limits')
    return fields
